#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CREATE DATA AND LOG DIRECTORIES
#=================================================

mkdir -p "$data_dir/blobs"
mkdir -p "/var/log/$app"

#=================================================
# COPY APP SOURCE
#=================================================

cp -ar "$YNH_APP_BASEDIR/sources/filedrop/." "$install_dir/"

#=================================================
# PYTHON VIRTUALENV
#=================================================

filedrop_install_dependencies

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_add_systemd_config
ynh_add_nginx_config

#=================================================
# PERMISSIONS
#=================================================

chown -R $app:www-data "$install_dir"
chown -R $app:$app "$data_dir"
chmod 750 "$data_dir"
chown $app:$app "/var/log/$app"

#=================================================
# LOGROTATE
#=================================================

ynh_use_logrotate

#=================================================
# START APP
#=================================================

yunohost service add $app --description="FileDrop ephemeral file transfer" --log="/var/log/$app/$app.log"

ynh_systemd_action --service_name=$app --action=start --log_path="/var/log/$app/$app.log" --line_match="Listening at" --timeout=60
