#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE FILES
#=================================================

ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="$data_dir"

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
ynh_restore_file --origin_path="/etc/logrotate.d/$app" --not_mandatory

#=================================================
# PERMISSIONS AND SERVICE
#=================================================

chown -R $app:www-data "$install_dir"
chown -R $app:$app "$data_dir"
chmod 750 "$data_dir"

systemctl enable $app.service --quiet
yunohost service add $app --description="FileDrop ephemeral file transfer" --log="/var/log/$app/$app.log"

ynh_systemctl --service=$app --action=start --log_path="systemd" --line_match="Listening at"
