#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SERVICE
#=================================================

ynh_systemd_action --service_name=$app --action=stop

#=================================================
# REFRESH APP SOURCE
#=================================================

mkdir -p "$data_dir/blobs"
mkdir -p "/var/log/$app"

ynh_secure_remove --file="$install_dir" --force
mkdir -p "$install_dir"
cp -ar "$YNH_APP_BASEDIR/sources/filedrop/." "$install_dir/"

#=================================================
# PYTHON VIRTUALENV
#=================================================

filedrop_install_dependencies

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_add_systemd_config
ynh_add_nginx_config
ynh_use_logrotate

chown -R $app:www-data "$install_dir"
chown -R $app:$app "$data_dir"
chmod 750 "$data_dir"
chown $app:$app "/var/log/$app"

#=================================================
# RESTART APP
#=================================================

ynh_systemd_action --service_name=$app --action=start --log_path="/var/log/$app/$app.log" --line_match="Listening at" --timeout=60
